### ISSUE TITLE
Implement tebako packaging mechanism

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#1]
The goal is to package a language interpreter with its dependencies and packages into a single executable.

We will implement something similar to https://github.com/metanorma/ruby-packer in this manner:
1. Use vanilla Ruby, redirect file calls to the internal packaged file system
2. Package the Ruby runtime, its dependencies and packages (i.e. gems) in a DwarFS system.
3. Adopt code from ruby-packer that allows detecting gems and consolidate necessary files.

The flow goes:

1. Package the filesystem. Write all files (Ruby binary, gems, compiled gems) into dwarFS, store the dwarFS file somewhere, then compress the dwarFS file.
2. Embed this compressed dwarFS file into the executable. We can directly link it using mechanisms described here:
  * https://codeplea.com/embedding-files-in-c-programs
  * https://developers.redhat.com/blog/2019/07/05/how-to-store-large-amounts-of-data-in-a-program
  * The `incbin` macro can be used here for simplicity: https://github.com/graphitemaster/incbin
3. On execution, the code runs dwarFS and opens the compressed file with memory allocation of the full size (in read-only mode).
4. Then execute the Ruby from the dwarFS package.

Originally from: https://github.com/metanorma/ruby-packer/issues/16

**Comment by maxirmx** [comment]
Ruby-packer uses libsquashfs which is an SDK specially designed to provide for build-in SquashFS support in the application.
DwarFS does not include any SDK.  There is a FUSE driver that can be adjusted and linked into an application.
It is not something envisioned or supported by the author and doing it basically means **very hard fork** with limited options to incorporated further versions of DwarFS

**Comment by ronaldtse** [comment]
@maxirmx libsquashfs was written by the author of ruby-packer -- just to implement ruby-packer. The method he tool was to simplify the existing SquashFS FUSE driver into a library. I believe we can do the same for DwarFS using the existing FUSE driver as a basis.

The author of DwarFS has indicated this usage can be supported and I believe he is open to such extension.

**Comment by maxirmx** [comment]
We need to split _dwarfs.cpp_ and _dwarfs_ applications into:
1) "_libdwarfsfuse_" that includes _run_fuse_ function  and filesystem operations -- _op_init ... op_getxattr_ 
      This new libary will be embeddable dwarfs fuse driver
     _libdwarfsfuse_ shall staically link existing _libdwarfs_ and other libraries (?? if possible)
2) Smaller _dwarfs_ application that does argument parsing (_main_ and _run_dwarfs_ functions)

**Comment by ronaldtse** [comment]
Do you mean `libdwarfsfuse` or `libdwarfs`?

Why do we need a "smaller dwarfs application"? We can do image builds directly using the existing dwarfs?

**Comment by maxirmx** [comment]
**Task list as of Aug 20, 2021**

- [ ] 1. Adopt custom ruby build from ruby-packager with version upgrade to 2.7  (1 week)
- [ ] 2. Adopt ruby script that discovers ruby dependencies (1 week)
_At this point we shall be able to create packaged ruby executable manually. It will have dependency on fuse_
- [ ] 3. Develop libdwarfs (like libsquashfs) that will allow to use dwarfs without fuse  (1 week)
- [ ] 4. Develop tests for libdwarfs (No 3)  (1 week)
- [ ] 5. Adjust custom ruby (No 1) so that it uses dwarfs using libdwarfs (No 3).   This build shall be reusable  and work for any ruby application to be packaged.  (1 week)
- [ ] 6. Develop tests for custom ruby with custom file operations (No 5)    (1 week)
_At this point we shall be able to create packaged ruby executable manually  without dependencies on fuse_

**Comment by ronaldtse** [comment]
@maxirmx can you help split the tasks into individual issues and link them back here? It's easier to manage that way. Thanks.

**Comment by maxirmx** [comment]
> @maxirmx can you help split the tasks into individual issues and link them back here? It's easier to manage that way. Thanks.

Done

**Comment by ronaldtse** [comment]
Thanks! I've also cleaned up the list for presentation.
